### ISSUE TITLE
Can not run

### ISSUE THREAD

**Issue by sitexa** [edge/cyc#1]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.1.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'owner',
1 verbose cli   'ls',
1 verbose cli   'Mycycapp' ]
2 info using npm@3.4.1
3 info using node@v5.1.0
4 silly mapToRegistry name Mycycapp
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry uri https://registry.npmjs.org/Mycycapp
8 verbose request uri https://registry.npmjs.org/Mycycapp
9 verbose request no auth needed
10 info attempt registry request try #1 at 11:22:08 AM
11 verbose request id c27cc123b20bf120
12 http request GET https://registry.npmjs.org/Mycycapp
13 http 404 https://registry.npmjs.org/Mycycapp
14 verbose headers { 'content-type': 'application/json',
14 verbose headers   'cache-control': 'max-age=0',
14 verbose headers   'content-length': '2',
14 verbose headers   'accept-ranges': 'bytes',
14 verbose headers   date: 'Wed, 25 Nov 2015 03:22:09 GMT',
14 verbose headers   via: '1.1 varnish',
14 verbose headers   age: '0',
14 verbose headers   connection: 'keep-alive',
14 verbose headers   'x-served-by': 'cache-sin6924-SIN',
14 verbose headers   'x-cache': 'MISS',
14 verbose headers   'x-cache-hits': '0',
14 verbose headers   'x-timer': 'S1448421729.718299,VS0,VE253' }
15 silly get cb [ 404,
15 silly get   { 'content-type': 'application/json',
15 silly get     'cache-control': 'max-age=0',
15 silly get     'content-length': '2',
15 silly get     'accept-ranges': 'bytes',
15 silly get     date: 'Wed, 25 Nov 2015 03:22:09 GMT',
15 silly get     via: '1.1 varnish',
15 silly get     age: '0',
15 silly get     connection: 'keep-alive',
15 silly get     'x-served-by': 'cache-sin6924-SIN',
15 silly get     'x-cache': 'MISS',
15 silly get     'x-cache-hits': '0',
15 silly get     'x-timer': 'S1448421729.718299,VS0,VE253' } ]
16 error owner ls Couldn't get owner data Mycycapp
17 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/Mycycapp
17 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
17 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
17 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
17 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:198:22)
17 verbose stack     at emitTwo (events.js:87:13)
17 verbose stack     at Request.emit (events.js:172:7)
17 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1082:10)
17 verbose stack     at emitOne (events.js:82:20)
17 verbose stack     at Request.emit (events.js:169:7)
17 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1009:12)
18 verbose statusCode 404
19 verbose pkgid Mycycapp
20 verbose cwd /Users/xnpeng/NodeJsProjects/Mycycapp
21 error Darwin 14.5.0
22 error argv "/usr/local/Cellar/node/5.1.0/bin/node" "/usr/local/bin/npm" "owner" "ls" "Mycycapp"
23 error node v5.1.0
24 error npm  v3.4.1
25 error code E404
26 error 404 Registry returned 404 for GET on https://registry.npmjs.org/Mycycapp
26 error 404
26 error 404 'Mycycapp' is not in the npm registry.
26 error 404 Your package name is not valid, because
26 error 404
26 error 404  1. name can no longer contain capital letters
26 error 404
26 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]

**Comment by alkhe** [comment]
Sorry for the delay. Can you post the steps to reproduce this problem?

**Comment by alkhe** [comment]
@sitexa is is possible that you tried `npm install Mycycapp`? It's not in the registry.

The proper way to scaffold a project is to run `cyc` and then enter your project name and directory name (defaults to project name).
