### ISSUE TITLE
ES6 relative path imports

### ISSUE THREAD

**Issue by alexej-d** [edge/cyc#11]
Hey, nice project, thanks for your work.
Maybe I am doing something wrong but trying to import my own modules in /src/js/index.js or main.js will give me "Module not found" errors. This breaks the npm tasks `import api from './api';` while `import api from './src/js/api';` works but gives me errors further down the road …

**Comment by alkhe** [comment]
This problem's actually been bugging me for a while, and webpack isn't very cooperative with this kind of thing. There are a few more things I've yet to try, so hang in there.

**Comment by alkhe** [comment]
@alexej-d fixed in #12, but #14 is related.
